name: Test build on every (branch) commit
on:
  # workflow_dispatch
 push:
    branches:
      - dev
 pull_request:
    branches:
      - dev

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    needs: harden_security
    steps:
      # Get the dev branch
      - uses: actions/checkout@v3

      # Set up node
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'
      - run: yarn install

  tsc:
    name: tsc
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: install node v12
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: yarn install
      run: yarn install
    - name: tsc
      uses: icrawl/action-tsc@v1

  harden_security:
    name: Harden Security
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # v2.3.4
      - name: Ensure SHA pinned actions
        uses: zgosalvez/github-actions-ensure-sha-pinned-actions@v2 # Replace this
        with:
          allowlist: |
            aws-actions/
            docker/login-action
