name: Test build on every (branch) commit
on:
  # workflow_dispatch
 push:
    branches:
      - dev
 pull_request:
    branches:
      - dev

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      # Get the dev branch
      - uses: actions/checkout@v3
      # Using SHA's keys
      - uses: actions/javascript-action@a824008085750b8e136effc585c3cd6082bd575f

      # Set up node
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'
      - run: yarn install

  tsc:
    name: tsc
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: install node v12
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: yarn install
      run: yarn install
    - name: tsc
      uses: icrawl/action-tsc@v1
