name: studiographene-ci

on:
  pull_request: {}
  push:
    branches: ["master", "main", "dev"]
  workflow_dispatch:

jobs:
  call-workflow:
    uses: studiographene/nodejs-ci/.github/workflows/ci.yml@master
    with:
      project_name: test-cicd
      package_manager: yarn
      build_command: yarn run build
      lint_command: yarn run lint
      excluded_jobs: docker
    secrets: inherit
    permissions: write-all
