
name: Test build on every (branch) commit
on:
  # workflow_dispatch
  pull_request:
  push:
    branches:
      - dev

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      # Get the dev branch
      - uses: actions/checkout@v3

      # Set up node
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'
      - run: yarn install

  tsc:
    name: tsc
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: install node v12
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: yarn install
      run: yarn install
    - name: tsc
      uses: icrawl/action-tsc@v1
